
export const FETCH_REQUEST="FETCH_REQUEST"
export const FETCH_REQUEST_SUCCESS="FETCH_REQUEST_SUCCESS"

export const UPDATE_USER_REQUEST="UPDATE_USER_REQUEST"
export const ADD_USER_REQUEST="ADD_USER_REQUEST"
export const DELETE_USER_REQUEST="DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS"

export const REQUEST_SUCCESS ="REQUEST_SUCCESS"
export const REQUEST_FAILURE="REQUEST_FAILURE"

