export const FETCH_BOOK_REQUEST="FETCH_BOOK_REQUEST"

export const UPDATE_BOOK_REQUEST="UPDATE_BOOK_REQUEST"
export const CREATE_BOOK_REQUEST="CREATE_BOOK_REQUEST"

export const REQUEST_SUCCESS ="REQUEST_SUCCESS"
export const REQUEST_FAILURE="REQUEST_FAILURE"

